# Generated by Django 5.1.1 on 2024-10-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemodels', '0002_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField()),
                ('season_name', models.CharField(max_length=255)),
                ('season_year', models.CharField(max_length=9)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='basemodels.tournament')),
            ],
        ),
    ]
